### ISSUE TITLE
modes_rx SBS-1 crashes on Linux mint 16 x64

### ISSUE THREAD

**Issue by engink1981** [bistromath/gr-air-modes#64]
The app crashes after 1 hour running.

Traceback:

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/air_modes/zmq_socket.py", line 101, in run
    self._pubsub[address] = msg
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/pubsub.py", line 52, in __setitem__
    sub(val)
  File "/usr/local/lib/python2.7/dist-packages/air_modes/parse.py", line 433, in publish
    pub["type%i_dl" % ret.data.get_type()] = ret
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/pubsub.py", line 52, in __setitem__
    sub(val)
  File "/usr/local/lib/python2.7/dist-packages/air_modes/sbs1.py", line 95, in output
    sbs1_msg = self.parse(msg)
  File "/usr/local/lib/python2.7/dist-packages/air_modes/sbs1.py", line 142, in parse
    outmsg = self.pp4(msg.data, msg.ecc)
  File "/usr/local/lib/python2.7/dist-packages/air_modes/sbs1.py", line 165, in pp4
    aircraft_id = self.get_aircraft_id(ecc)
  File "/usr/local/lib/python2.7/dist-packages/air_modes/sbs1.py", line 86, in get_aircraft_id
    for icao, _id in self._aircraft_id_map.iteritems():
RuntimeError: dictionary changed size during iteration

Some details:
USRP B210 / UHD
Linux Mint 16 x64
Python 2.7.5+
linux; GNU C++ version 4.8.1; Boost_1.53
gnuradio 3.7.3

**Comment by macsmith** [comment]
Hi,  bistromath, will you be able to have a look at this problem?
It's a great programme, just needs the dictionary problem fixed so it can run continuously.

TIA
Ian

**Comment by phileasF** [comment]
Hi,

for a quick fix you can use this patch:

    --- old/python/sbs1.py       2015-05-02 00:56:50.276933440 +0200
    +++ new/python/sbs1.py       2015-05-02 00:56:54.039949968 +0200
    @@ -83,7 +83,7 @@
         # dictionary is getting too large.
         if len(self._aircraft_id_map) > 1e4:
           minimum = min(self._aircraft_id_map.values()) + (len(self._aircraft_id_map) - 1e4)
    -      for icao, _id in self._aircraft_id_map.iteritems():
    +      for icao, _id in self._aircraft_id_map.items():
             if _id < minimum:
                 del self._aircraft_id_map[icao]

**Comment by engink1981** [comment]
dear phileasF,
I have applied your patch,but after 70 minutes, it gives error given below,

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/air_modes/zmq_socket.py", line 101, in run
    self._pubsub[address] = msg
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/pubsub.py", line 52, in __setitem__
    sub(val)
  File "/usr/local/lib/python2.7/dist-packages/air_modes/parse.py", line 433, in publish
    pub["type%i_dl" % ret.data.get_type()] = ret
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/pubsub.py", line 52, in __setitem__
    sub(val)
  File "/usr/local/lib/python2.7/dist-packages/air_modes/msprint.py", line 161, in handle17
    [velocity, heading, vert_spd] = air_modes.parseBDS09_1(msg.data)
  File "/usr/local/lib/python2.7/dist-packages/air_modes/parse.py", line 338, in parseBDS09_1
    ns_vel <<= 2
TypeError: unsupported operand type(s) for <<=: 'float' and 'int'

**Comment by phileasF** [comment]
Hi,

this seems to be a different issue. It only seems to happen, when a certain kind of message is received. But I do not know much about the ADB-S protocol.
The code should be easy to fix. But I have to test it before I can give you a patch.

**Comment by bistromath** [comment]
I have fixes for both issues and will be updating shortly. Sorry for the
delay.

**Comment by bistromath** [comment]
Both issues have fixes committed. Please give the latest master branch a
try and verify it fixes your problem.

Best,
Nick
