### ISSUE TITLE
QtWebKit no longer in PyQt4 (for example, in Ubuntu 16.10)

### ISSUE THREAD

**Issue by ac2ie** [bistromath/gr-air-modes#98]
tom@kudu:~$ modes_gui
Traceback (most recent call last):
  File "/usr/local/bin/modes_gui", line 24, in <module>
    from PyQt4 import QtCore,QtGui,QtWebKit
ImportError: cannot import name QtWebKit

Work-arounds on the web suggest you can get it to work by manually installing an earlier version of the PyQt4 package (I didn't try this), or use QtWebKit from PySide (I tried this but it didn't work):

tom@kudu:~$ modes_gui
Traceback (most recent call last):
  File "/usr/local/bin/modes_gui", line 33, in <module>
    from air_modes.modes_rx_ui import Ui_MainWindow
  File "/usr/local/lib/python2.7/dist-packages/air_modes/modes_rx_ui.py", line 428, in <module>
    from QtWebKit.qwebview import QWebView
ImportError: No module named QtWebKit.qwebview

Links to the Debian 8 discussion seems to say developers need to switch to PyQt5.

**Comment by Krastanov** [comment]
Commenting out a few lines inside of the file permitted me to launch the software without crashes. The map does not work, as it is the part that requires the WebView.

I will see whether I can spend some time on making it work with PyQt5.

@ac2ie , could you please share the link to the Debian 8 discussion you mentioned?

**Comment by ac2ie** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784513

User TheCompiler suggest QtWebKit will eventually be removed from PyQt5: http://askubuntu.com/questions/840318/importerror-no-module-named-pyqt4-qtwebkit

**Comment by niehauss** [comment]
Krastanov, since I am unexperienced with pyhon but the bug hurts me too: can you suggest which lines to commemt out?


Thanks, 

Sebastian

**Comment by bistromath** [comment]
Not a lot I can do about this other than reimplement the map outside QtWebKit. I'll make the map support conditional on having QtWebKit installed, so it at least runs when the map is unavailable.

**Comment by Krastanov** [comment]
There are some options that do not require reimplementation, just renaming some of the imports and fixing some API calls. I am sorry for the vagueness, I will try to respond more completely briefly.

**Comment by JWCampbell** [comment]
Any update on this issue? If nobody else is working on it, I will probably take a try at it, but it would be better if I knew I wasn't duplicating another persons effort.

**Comment by bistromath** [comment]
I was holding off on this until Gnuradio finally moves to Python 3. Also
because I'm lazy. =) If you'd like to take a stab at it I'm happy to merge
it in.

**Comment by jayeye** [comment]
no progress on this bug in two years? The problem persists. Does nobody use qt-air-modes?

**Comment by bistromath** [comment]
The modes_gui component was never much used, and I haven't had the
bandwidth to maintain it to keep up with GUI toolkit changes. I should
probably deprecate it.
